### PR TITLE
fix typo in delete action

### PR DESCRIPTION
**Pull request by joshbrand**
resolves `NoMethodError: undefined method `exist?' for Chef::Provider::File:Class` error

### CODE REVIEW

**Comment by joshbrand** [comment]
okay, now this is ready.  fixed a scoping problem with File too :)

**Comment by tas50** [comment]
Exists is the legacy method in ruby. :: is correct but exist should work fine

**Comment by tas50** [comment]
I fixed this on master. I'll cut a release when I'm not on my phone

**Comment by joshbrand** [comment]
my mistake.  thanks for the quick response :+1:

**Pull request closed without merging**
